services:
  app:
    image: ${DOCKER_IMAGE}
    container_name: pharmacy-app
    restart: always
    env_file: .env
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - TZ=Asia/Seoul
    logging:
      options:
        max-size: "10m"
        max-file: "3"
